package domain

import (
	"context"
	"time"
)

// MessageSender represents who authored the message.
type MessageSender string

const (
	SenderUser   MessageSender = "user"
	SenderModel  MessageSender = "model"
	SenderSystem MessageSender = "system"
)

// Attachment represents multimodal files sent with a chat message (images, PDFs, documents).
type Attachment struct {
	Name       string `json:"name"`                  // e.g. "math_homework.jpg"
	MimeType   string `json:"mime_type"`             // e.g. "image/jpeg", "application/pdf"
	URL        string `json:"url,omitempty"`         // GCS or external URI
	DataBase64 string `json:"data_base64,omitempty"` // Inline base64 payload for direct upload
	SizeBytes  int64  `json:"size_bytes,omitempty"`
}

// RAGSource represents a grounded document citation retrieved by the RAG engine.
type RAGSource struct {
	Title   string  `json:"title"`
	URI     string  `json:"uri,omitempty"`
	Snippet string  `json:"snippet"`
	Score   float64 `json:"score,omitempty"`
}

// StructuredAIResponse represents the structured formatted output generated by Gemini.
type StructuredAIResponse struct {
	ReplyText     string       `json:"reply_text"`               // Main conversational and educational reply
	KeyTakeaways  []string     `json:"key_takeaways,omitempty"`  // Core academic or conceptual points
	ActionItems   []string     `json:"action_items,omitempty"`   // Recommended practice, next steps, or reflection exercises
	EmotionalTone string       `json:"emotional_tone,omitempty"` // e.g. "Encouraging & Warm", "Mindful & Calming"
	Sources       []RAGSource  `json:"sources,omitempty"`        // RAG references if retrieved
	// Attachments carries images produced via the "generate_educational_image" tool
	// call, gathered within the same Gemini turn (see GenerateChatResponse) so they
	// reach the student as part of this one reply rather than a separate follow-up
	// message. Empty when no image was requested.
	// PendingImagePrompt is set instead of Attachments when the model called
	// "generate_educational_image" this turn: image generation is slow enough (several
	// seconds) that it must not hold up the text reply, so GenerateChatResponse never
	// runs it itself — it just reports the prompt back to the caller (chat.Service),
	// which saves the text reply immediately and generates the image afterward in the
	// background (see ChatMessage.ImageGenerating).
	PendingImagePrompt string `json:"-"`
}

// ChatMessage represents a single message in a conversation.
type ChatMessage struct {
	ID          string        `json:"id" firestore:"id"`
	SessionID   string        `json:"session_id" firestore:"session_id"`
	Sender      MessageSender `json:"sender" firestore:"sender"`
	Content     string        `json:"content" firestore:"content"`
	Attachments []Attachment  `json:"attachments,omitempty" firestore:"attachments,omitempty"`
	// ImageGenerating is true from the moment this message is first saved (its text
	// reply already decided to call generate_educational_image) until the background
	// generation finishes and this same message is re-saved with Attachments set. The
	// frontend polls while this is true and shows a "generating image" placeholder —
	// see app/student/page.tsx.
	ImageGenerating bool      `json:"image_generating,omitempty" firestore:"image_generating,omitempty"`
	SessionTitle    string    `json:"session_title,omitempty" firestore:"-"`
	CreatedAt       time.Time `json:"created_at" firestore:"created_at"`
}

// ChatSession represents an active or historical conversation session for a student.
// LiveTalkSessionTitlePrefix marks a ChatSession as having originated from a spoken
// Live Talk call rather than typed chat (see streaming.Handler, which sets this title
// when creating the session). Checked via strings.HasPrefix rather than a boolean
// field since sessions have no dedicated "kind" field of their own.
const LiveTalkSessionTitlePrefix = "🎙️ Live Talk"

type ChatSession struct {
	ID             string    `json:"id" firestore:"id"`
	StudentID      string    `json:"student_id" firestore:"student_id"`
	Title          string    `json:"title" firestore:"title"`
	ContextSummary string    `json:"context_summary,omitempty" firestore:"context_summary,omitempty"`
	MessageCount   int       `json:"message_count" firestore:"message_count"`
	CreatedAt      time.Time `json:"created_at" firestore:"created_at"`
	UpdatedAt      time.Time `json:"updated_at" firestore:"updated_at"`
}

// CreateSessionRequest is the payload to start a new chat conversation.
type CreateSessionRequest struct {
	Title string `json:"title,omitempty"`
}

// RenameSessionRequest is the payload to update a chat session's title.
type RenameSessionRequest struct {
	Title string `json:"title"`
}

// SendMessageRequest is the payload to send a message to Buddy AI.
type SendMessageRequest struct {
	Content     string       `json:"content"`
	Attachments []Attachment `json:"attachments,omitempty"`
}

// ChatRepository provides data access for chat sessions, messages, memory, and prompts.
type ChatRepository interface {
	// Sessions
	CreateSession(ctx context.Context, session *ChatSession) error
	GetSession(ctx context.Context, sessionID string) (*ChatSession, error)
	ListSessions(ctx context.Context, studentID string, limit int) ([]*ChatSession, error)
	// ListAllSessionsForStudent returns every session belonging to a student, unbounded
	// by ListSessions' page-size cap. Used for progress/analytics aggregation, where
	// undercounting a student's true session count would defeat the point.
	ListAllSessionsForStudent(ctx context.Context, studentID string) ([]*ChatSession, error)
	UpdateSession(ctx context.Context, session *ChatSession) error
	DeleteSession(ctx context.Context, sessionID string) error
	// DeleteSessionsByStudent cascades to every session (and each session's messages)
	// belonging to studentID, unbounded by the page-size limit ListSessions enforces.
	// Used when a user account is deleted so no chat history is left orphaned.
	DeleteSessionsByStudent(ctx context.Context, studentID string) error

	// Messages
	// SaveMessage upserts by message.ID: saving a message whose ID already exists
	// replaces it in place rather than creating a duplicate. Used both to create a
	// new message and (for ImageGenerating messages) to update one in place once
	// background image generation finishes.
	SaveMessage(ctx context.Context, message *ChatMessage) error
	// GetMessage looks up a single message by ID, used to re-fetch and update one
	// after background image generation completes (see ChatMessage.ImageGenerating).
	GetMessage(ctx context.Context, messageID string) (*ChatMessage, error)
	ListMessages(ctx context.Context, sessionID string, limit int) ([]*ChatMessage, error)
	DeleteMessage(ctx context.Context, messageID string) error

	// Personal Intelligence Memory
	GetPersonalIntelligence(ctx context.Context, studentID string) (*StudentPersonalIntelligence, error)
	SavePersonalIntelligence(ctx context.Context, memory *StudentPersonalIntelligence) error
	DeletePersonalIntelligence(ctx context.Context, studentID string) error

	// System Prompts — chat and Live Talk each have their own independently active
	// prompt (see PromptKind), never sharing a document.
	GetActivePrompt(ctx context.Context, kind PromptKind) (*SystemPrompt, error)
	SavePrompt(ctx context.Context, prompt *SystemPrompt) error
}
