package domain

import (
	"context"
	"time"
)

// MessageSender represents who authored the message.
type MessageSender string

const (
	SenderUser   MessageSender = "user"
	SenderModel  MessageSender = "model"
	SenderSystem MessageSender = "system"
)

// Attachment represents multimodal files sent with a chat message (images, PDFs, documents).
type Attachment struct {
	Name       string `json:"name"`                  // e.g. "math_homework.jpg"
	MimeType   string `json:"mime_type"`             // e.g. "image/jpeg", "application/pdf"
	URL        string `json:"url,omitempty"`         // GCS or external URI
	DataBase64 string `json:"data_base64,omitempty"` // Inline base64 payload for direct upload
	SizeBytes  int64  `json:"size_bytes,omitempty"`
}

// RAGSource represents a grounded document citation retrieved by the RAG engine.
type RAGSource struct {
	Title   string  `json:"title"`
	URI     string  `json:"uri,omitempty"`
	Snippet string  `json:"snippet"`
	Score   float64 `json:"score,omitempty"`
}

// StructuredAIResponse represents the structured formatted output generated by Gemini.
type StructuredAIResponse struct {
	ReplyText     string      `json:"reply_text"`               // Main conversational and educational reply
	KeyTakeaways  []string    `json:"key_takeaways,omitempty"`  // Core academic or conceptual points
	ActionItems   []string    `json:"action_items,omitempty"`   // Recommended practice, next steps, or reflection exercises
	EmotionalTone string      `json:"emotional_tone,omitempty"` // e.g. "Encouraging & Warm", "Mindful & Calming"
	Sources       []RAGSource `json:"sources,omitempty"`        // RAG references if retrieved
}

// ChatMessage represents a single message in a conversation.
type ChatMessage struct {
	ID           string        `json:"id" firestore:"id"`
	SessionID    string        `json:"session_id" firestore:"session_id"`
	Sender       MessageSender `json:"sender" firestore:"sender"`
	Content      string        `json:"content" firestore:"content"`
	Attachments  []Attachment  `json:"attachments,omitempty" firestore:"attachments,omitempty"`
	SessionTitle string        `json:"session_title,omitempty" firestore:"-"`
	CreatedAt    time.Time     `json:"created_at" firestore:"created_at"`
}

// ChatSession represents an active or historical conversation session for a student.
type ChatSession struct {
	ID             string    `json:"id" firestore:"id"`
	StudentID      string    `json:"student_id" firestore:"student_id"`
	Title          string    `json:"title" firestore:"title"`
	ContextSummary string    `json:"context_summary,omitempty" firestore:"context_summary,omitempty"`
	MessageCount   int       `json:"message_count" firestore:"message_count"`
	CreatedAt      time.Time `json:"created_at" firestore:"created_at"`
	UpdatedAt      time.Time `json:"updated_at" firestore:"updated_at"`
}

// CreateSessionRequest is the payload to start a new chat conversation.
type CreateSessionRequest struct {
	Title string `json:"title,omitempty"`
}

// RenameSessionRequest is the payload to update a chat session's title.
type RenameSessionRequest struct {
	Title string `json:"title"`
}

// SendMessageRequest is the payload to send a message to Buddy AI.
type SendMessageRequest struct {
	Content     string       `json:"content"`
	Attachments []Attachment `json:"attachments,omitempty"`
}

// ChatRepository provides data access for chat sessions, messages, memory, and prompts.
type ChatRepository interface {
	// Sessions
	CreateSession(ctx context.Context, session *ChatSession) error
	GetSession(ctx context.Context, sessionID string) (*ChatSession, error)
	ListSessions(ctx context.Context, studentID string, limit int) ([]*ChatSession, error)
	UpdateSession(ctx context.Context, session *ChatSession) error
	DeleteSession(ctx context.Context, sessionID string) error
	// DeleteSessionsByStudent cascades to every session (and each session's messages)
	// belonging to studentID, unbounded by the page-size limit ListSessions enforces.
	// Used when a user account is deleted so no chat history is left orphaned.
	DeleteSessionsByStudent(ctx context.Context, studentID string) error

	// Messages
	SaveMessage(ctx context.Context, message *ChatMessage) error
	ListMessages(ctx context.Context, sessionID string, limit int) ([]*ChatMessage, error)
	DeleteMessage(ctx context.Context, messageID string) error

	// Personal Intelligence Memory
	GetPersonalIntelligence(ctx context.Context, studentID string) (*StudentPersonalIntelligence, error)
	SavePersonalIntelligence(ctx context.Context, memory *StudentPersonalIntelligence) error
	DeletePersonalIntelligence(ctx context.Context, studentID string) error

	// System Prompts
	GetActivePrompt(ctx context.Context) (*SystemPrompt, error)
	SavePrompt(ctx context.Context, prompt *SystemPrompt) error
	ListPrompts(ctx context.Context) ([]*SystemPrompt, error)
}
